name: Verify
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 23f2001550@ds.study.iitm.ac.in
        run: echo "Verified"
      - name: Create data
        run: echo "data" > cache.txt
      - name: Cache dependencies
        id: cache-step
        uses: actions/cache@v4
        with:
          path: cache.txt
          key: cache-0e2314c
      - name: prime-cache-0e2314c
        run: echo "Hit: ${{ steps.cache-step.outputs.cache-hit }}"
